### ISSUE TITLE
Support reading variables in the REPL's scope

### ISSUE THREAD

**Issue by cauefcr** [containous/yaegi#262]
It would be really useful to be able to read variables in the REPL, like e.g. IPython.

**Comment by mvertes** [comment]
Thanks for your request @cauefcr. Sorry, I don't get it. Could you provide more details and/or an example of what you want exactly ?
Thanks

**Comment by cauefcr** [comment]
Suppose i have this code:
```
package main

import (
	"fmt"
	"os"

	"go/build"
	"github.com/containous/yaegi/interp"
	"github.com/containous/yaegi/stdlib"
)

func main(){
	i := interp.New(interp.Options{GoPath: build.Default.GOPATH})
	val := 123
	_ = val
	fmt.Println("wow, repl now:")
	i.Repl(os.Stdin, os.Stdout)
	fmt.Println("repl quit")
}
```
I want, from inside the repl, to inspect the value of the val variable, i have no access to the context in the REPL scope.

**Comment by mvertes** [comment]
Thank you for the clarification, this is exactly the info I was missing.

So it is already possible to make variables from the host executable visible to the guest interpreter (the repl). Prior starting the repl, you can *Use* a symbol map containing the objects you want to export:

```go
i.Use(interp.Exports{
     "zzz": map[string]reflect.Value{
         "val": reflect.ValueOf(val),
     },
})
```

It creates a virtual package `"zzz"` in the context of the interpreter (you can provide any path you want instead of "zzz", be careful to collisions with other package names).

Then, in the repl, you just import `zzz` and you have access to the variable:

```console
> import "zzz"
> zzz.val
123
```

Note that if `val` is readonly and can not be modified from the interpreter. If you want to be able to modify `zzz` from the interpreter, make it addressable using the following pattern:

`"val": reflect.ValueOf(&val).Elem()`

By the way, this is exactly how all the objects from standard library (constants, variables, types, functions, interfaces) are made visible to the interpreter. The code generation for the wrappers is done by `goexports` in that case.

Hope it answsers your question.

**Comment by cauefcr** [comment]
This perfectly clarifies things, thank you!
