### ISSUE TITLE
go1.13 mod tidy

### ISSUE THREAD

**Issue by gargous** [containous/yaegi#743]
my golang version is 1.13.5 and when I run the sample with go mod tidy
it tells me：
github.com/containous/yaegi/stdlib imports hash/maphash: malformed module path "hash/maphash": missing dot in first path element

**Comment by mvertes** [comment]
Thanks for the report. I could reproduce it with `go1.13.12` as well. To me it is an issue of the `go mod tidy` command.

What happens here is that `hash/maphash` is a Go standard library module which has been introduced in `go1.14` and does not exist in `go1.13`. It is only imported by `stdlib/go1_14_hash_maphash.go`, and used when `yaegi` is built by `go1.14`. This file should be skipped by `go1.13.x`, due to the buildtag `// +build go1.14,!go1.15`, at the beginning of the file, and this is what happens when building yaegi with `go1.13`.

So it seems to be an issue of the `go mod tidy` command itself, which should not take this file into account when analyzing module dependencies, when running with `go1.13`.

**Comment by mvertes** [comment]
A corresponding issue opened at https://github.com/golang/go/issues/40067
